# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: jeffreyladish.com
email: secrets@jeffreyladish.com
description: >- # this means to ignore newlines until "baseurl:"
  "Applying the security mindset to everything."

baseurl: "/"
url: https://jeffreyladish.com
twitter_username: jeffladish
github_username: land-fish
minimal_mistakes_skin: default 
search: true

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.16.0"
# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-149364896-1"
    anonymize_ip: false # default

author:
  name   : "Jeffrey Ladish"
  avatar : "/assets/images/jeffrey1.jpg"
  bio    : "Applying the security mindset to everything."
  links:
    - label: "Medium"
      icon: "fas fa-fw fa-link"
      url: "https://medium.com/@landfish"
    - label: "jeffladish"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/jeffladish"
    - label: "land-fish"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/land-fish/"

footer:
  links:
    - label: "Medium"
      icon: "fas fa-fw fa-link"
      url: "https://medium.com/@landfish"
    - label: "jeffladish"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/jeffladish"
    - label: "land-fish"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/land-fish/"

defaults:
   # All 
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
      read_time: false 
      comments: true
      share: false 
      related: false 
        
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false 
      comments: true
      share: false 
      related: false 
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
